### ISSUE TITLE
Bildgrößen, Srcset, lazyloading

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/schweizer5#10]
Lazyloading + srcset = [Lazysizes](https://github.com/aFarkas/lazysizes)?

Automatische Bild-Optimierung + Erstellung von Bildgrößen per Webpack?
zB von
`content/images/schweizer5-eventlocation-frankfurt-1.jpg`
nach
`thumbnails/schweizer5-eventlocation-frankfurt-1-1800.jpg`

Specs:
- jpg
- 80% quality
- no crop

Breiten:
- 1800
- 1200
- 900
- 600

(ergibt schöne Pixelabmessungen bei 2:3 Formaten und ist von Stufe zu Stufe ca eine Verdoppelung der Pixel-Fläche, also ca auch Dateigröße)

**Comment by reneweiser** [comment]
[Commit](https://github.com/encoding-group/schweizer5/commit/5b35451fd86969ede124ead69c730780885b596d) unterstützt nun diese Anforderungen.
