### ISSUE TITLE
Use no-break-spaces between numbers (500<nbsp/>m)

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/schweizer5#14]

**Comment by reneweiser** [comment]
2864925d41084ea88cd2a93b64bd74b4491f4a07: This should be correct yes?

**Comment by moritzebeling** [comment]
Ah, die meisten Nummern sind ja in `em` s drin. dh man hätte das vielleicht auch mit CSS `white-space: no-break;` machen können. Aber so ist es ja schon fertig. Super!
