### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/schweizer5#20]

**Comment by moritzebeling** [comment]
@reneweiser 

Okay, hab ich hinzugefügt mit einem Webpack plugin namens [favicons-webpack-plugin](https://github.com/jantimon/favicons-webpack-plugin). Ich hoffe das war okay.

Ich hab dann mal bei dem build-process von Netlify reingeschaut und da sind ne Menge Warnungen. Auch GitHub zeigt eine Vulnerability an. War das auch schon vorher? Oder hab ich das jetzt verursacht?

**Comment by reneweiser** [comment]
> Ich hab dann mal bei dem deploy log von Netlify reingeschaut und da sind ne Menge Warnungen

Die Warnungen beziehen sich auf die Dateigröße von Assets die größer als 244 KiB sind. Webpack weißt aus Performancegründen darauf hin, steht auch so in der Console. Soweit ich das sehe, sind das allerdings alles Bilder, da kommt man ohne weiteres nicht drum herum. Insofern waren mir die Warnungen schon bekannt.

> Auch GitHub zeigt eine Vulnerability an. War das auch schon vorher? Oder hab ich das jetzt verursacht?

Da die [Vulnerability Alert für url-regex](https://github.com/encoding-group/schweizer5/network/alert/package-lock.json/url-regex/open) kam nachdem du das neue Plugin installiert hattes gehe ich mal davon aus, dass es eine dependency von favicons-webpack-plugin ist. Allerdings ist es bei NPM nicht als dependency gelistet. Da müsstest du mal schauen.

**Comment by reneweiser** [comment]
Vielleicht ist diese Warnung für uns auch garnicht relevant, da das Plugin nur im Buildprozess aktiv ist. Danach gibts ja nur static assets. #jamstack for the win! 👍

**Comment by moritzebeling** [comment]
Ja. also ich bekomm das auch irgendwie nicht weg. ist vielleicht (vorerst) nicht weiter schlimm
