### ISSUE TITLE
Use current paraport version

### ISSUE THREAD

**Issue by moritzebeling** [encoding-group/schweizer5#23]
Either by taking the most current code and put it directly into this page or by referencing a published package.

Keep in mind, that the version implemented here has a different speed multiplier (`0.15`) than the original (`0.05`). Since we have that new `multiply` option, that should be set to `3`, right?

Like:
```js
const paraport = new Paraport({
  multiply: 3
});
```

**Comment by moritzebeling** [comment]
Unfortunately I wasn’t able to do it and have no idea why this keeps happening:

<img width="518" alt="Bildschirmfoto 2020-07-21 um 00 14 00" src="https://user-images.githubusercontent.com/39742729/87991750-224dc680-cae7-11ea-9efd-f60fc5a6c1c1.png">

**Comment by reneweiser** [comment]
I cannot replicate this error on my end. The constructor seems to work fine when using a different multiplier like this.

**Comment by reneweiser** [comment]
997301c440c0af013ef2e5a730a5133bd8463a86 Updated paraport. Works fine for me.

**Comment by reneweiser** [comment]
@moritzebeling can you check if the problem is solved on your end, so we can merge this to master.

**Comment by moritzebeling** [comment]
Scrolling works fine, no errors

**Comment by reneweiser** [comment]
2f68419b23ad1f63d221cb75339622fed6c2b9a6 Updated to current paraport version
